### ISSUE TITLE
Language English

### ISSUE THREAD

**Issue by NewtTheWolf** [Asthegor/DinaLua#1]
it would be really great to have an english version of everything

**Comment by Asthegor** [comment]
First of all, thanks for your feed back and sorry for the inconvenience.

I'm a french programmer and it's easier for me to write everything in french rather than in english....

If you look at the code, every comments are in english.
This is only the comments on GitHub which are in french.

In the maintime, you can found any translated version of everything on the website [](https://dina.lacombedominique.com/).
You just have to select your prefered language and Google Translate will translate you everything 😉

I hope this will help you.

**Comment by Asthegor** [comment]
If you found some comment which are not in english, please send me an email (available on my website) or open an issue here.
I'll change it as soon as possible.
